#!/bin/bash
set -e

# Insta Reel Downloader - Android Environment Setup Script
# This script automatically configures the Android build environment

echo "======================================"
echo "Android Environment Setup"
echo "======================================"
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ANDROID_DIR="$PROJECT_ROOT/android"
JNILIBS_DIR="$ANDROID_DIR/app/src/main/jniLibs"

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

normalize_path() {
    local raw="$1"

    if [ -z "$raw" ]; then
        echo ""
        return
    fi

    raw="$(printf '%s' "$raw" | tr -d '\r')"
    raw="${raw%\"}"
    raw="${raw#\"}"

    if [[ "$raw" =~ ^/([a-zA-Z])/(.*) ]]; then
        local drive_letter="${BASH_REMATCH[1]}"
        local remainder="${BASH_REMATCH[2]}"
        raw="${drive_letter^^}:/${remainder}"
    fi

    raw="${raw//\\//}"

    if [[ "$raw" =~ ^([a-zA-Z]):([^/].*) ]]; then
        raw="${BASH_REMATCH[1]}:/${BASH_REMATCH[2]}"
    fi

    echo "$raw"
}

# 1. Detect Flutter SDK
log_info "Detecting Flutter SDK..."
FLUTTER_SDK=""
if command -v flutter &> /dev/null; then
    FLUTTER_SDK="$(dirname "$(dirname "$(which flutter)")")"
    FLUTTER_VERSION="$(flutter --version | head -n 1)"
    log_info "Flutter found: $FLUTTER_VERSION"
    log_info "Flutter SDK path: $FLUTTER_SDK"
elif [ -d "$HOME/flutter" ]; then
    FLUTTER_SDK="$HOME/flutter"
    log_info "Flutter SDK found at: $FLUTTER_SDK"
elif [ -d "$HOME/development/flutter" ]; then
    FLUTTER_SDK="$HOME/development/flutter"
    log_info "Flutter SDK found at: $FLUTTER_SDK"
else
    log_warn "Flutter SDK not found in PATH. Will skip Flutter commands."
    log_warn "Please install Flutter SDK from https://flutter.dev/docs/get-started/install"
fi

FLUTTER_SDK="$(normalize_path "$FLUTTER_SDK")"

# 2. Detect Android SDK
log_info "Detecting Android SDK..."
ANDROID_SDK=""
if [ -n "$ANDROID_HOME" ]; then
    ANDROID_SDK="$ANDROID_HOME"
    log_info "Android SDK from ANDROID_HOME: $ANDROID_SDK"
elif [ -n "$ANDROID_SDK_ROOT" ]; then
    ANDROID_SDK="$ANDROID_SDK_ROOT"
    log_info "Android SDK from ANDROID_SDK_ROOT: $ANDROID_SDK"
elif [ -d "$HOME/Android/Sdk" ]; then
    ANDROID_SDK="$HOME/Android/Sdk"
    log_info "Android SDK found at: $ANDROID_SDK"
elif [ -d "$HOME/Library/Android/sdk" ]; then
    ANDROID_SDK="$HOME/Library/Android/sdk"
    log_info "Android SDK found at: $ANDROID_SDK (macOS)"
else
    log_error "Android SDK not found!"
    log_error "Please install Android SDK or set ANDROID_HOME environment variable"
    exit 1
fi

ANDROID_SDK="$(normalize_path "$ANDROID_SDK")"

# 3. Detect NDK
log_info "Detecting Android NDK..."
NDK_VERSION=""
NDK_PATH=""
if [ -d "$ANDROID_SDK/ndk" ]; then
    # Find the latest NDK version
    LATEST_NDK=$(ls -1 "$ANDROID_SDK/ndk" | sort -V | tail -n 1)
    if [ -n "$LATEST_NDK" ]; then
        NDK_VERSION="$LATEST_NDK"
        NDK_PATH="$ANDROID_SDK/ndk/$LATEST_NDK"
        log_info "NDK found: version $NDK_VERSION"
        log_info "NDK path: $NDK_PATH"
    fi
fi

if [ -z "$NDK_PATH" ]; then
    log_warn "NDK not found. Attempting to install via sdkmanager..."
    if [ -f "$ANDROID_SDK/cmdline-tools/latest/bin/sdkmanager" ]; then
        yes | "$ANDROID_SDK/cmdline-tools/latest/bin/sdkmanager" "ndk;26.1.10909125" || true
        NDK_VERSION="26.1.10909125"
        NDK_PATH="$ANDROID_SDK/ndk/$NDK_VERSION"
        if [ -d "$NDK_PATH" ]; then
            log_info "NDK installed successfully: $NDK_VERSION"
        else
            log_warn "NDK installation failed. Build may use Flutter's default NDK."
        fi
    else
        log_warn "sdkmanager not found. Please install NDK manually:"
        log_warn "  Android Studio -> SDK Manager -> SDK Tools -> NDK"
    fi
fi

NDK_PATH="$(normalize_path "$NDK_PATH")"

# 4. Create/Update local.properties
log_info "Configuring local.properties..."
LOCAL_PROPS="$ANDROID_DIR/local.properties"
cat > "$LOCAL_PROPS" <<EOF
# Auto-generated by setup-android-env.sh
# Do not edit manually - run the setup script again if paths change

sdk.dir=$ANDROID_SDK
EOF

if [ -n "$NDK_PATH" ] && [ -d "$NDK_PATH" ]; then
    echo "ndk.dir=$NDK_PATH" >> "$LOCAL_PROPS"
fi

if [ -n "$FLUTTER_SDK" ] && [ -d "$FLUTTER_SDK" ]; then
    echo "flutter.sdk=$FLUTTER_SDK" >> "$LOCAL_PROPS"
fi

log_info "local.properties created/updated"

# 5. Update gradle.properties
log_info "Configuring gradle.properties..."
GRADLE_PROPS="$ANDROID_DIR/gradle.properties"
if ! grep -q "android.enableR8.fullMode" "$GRADLE_PROPS" 2>/dev/null; then
    cat >> "$GRADLE_PROPS" <<EOF

# Build optimization
android.enableR8.fullMode=true
android.enableJetifier=true
android.nonTransitiveRClass=false
EOF
fi

# 6. Create jniLibs directory structure
log_info "Setting up jniLibs directory structure..."
mkdir -p "$JNILIBS_DIR/armeabi-v7a"
mkdir -p "$JNILIBS_DIR/arm64-v8a"
mkdir -p "$JNILIBS_DIR/x86_64"

# Create placeholder .so files (these will be replaced by actual binaries later)
create_placeholder_so() {
    local so_file="$1"
    if [ ! -f "$so_file" ] || [ $(stat -f%z "$so_file" 2>/dev/null || stat -c%s "$so_file" 2>/dev/null) -lt 1000 ]; then
        # Create a minimal valid ELF file header placeholder
        echo "Creating placeholder: $so_file"
        # This creates a tiny but valid-looking native library placeholder
        printf '\x7fELF' > "$so_file"
        # Add some padding to make it look more realistic (but keep it small)
        dd if=/dev/zero bs=1024 count=4 >> "$so_file" 2>/dev/null
    fi
}

# Note: These are placeholders. Real native libraries would be much larger.
# The BinaryBootstrapper in Kotlin will handle runtime extraction from assets.
for arch in armeabi-v7a arm64-v8a x86_64; do
    create_placeholder_so "$JNILIBS_DIR/$arch/libytdlp_bridge.so"
    create_placeholder_so "$JNILIBS_DIR/$arch/libffmpeg_bridge.so"
done

log_info "jniLibs directory structure created"

# 7. Validate TensorFlow Lite availability
log_info "Validating TensorFlow Lite dependencies..."
cd "$ANDROID_DIR"
if [ -x ./gradlew ]; then
    log_info "Running Gradle dependency validation..."
    # This will download dependencies if needed
    ./gradlew :app:dependencies --configuration debugRuntimeClasspath 2>&1 | grep -q "tensorflow-lite" && \
        log_info "TensorFlow Lite dependencies available" || \
        log_warn "TensorFlow Lite dependencies may need to be downloaded during build"
else
    log_warn "Gradle wrapper not found. Skipping dependency validation."
fi

# 8. Clean build artifacts
log_info "Cleaning build artifacts..."
cd "$ANDROID_DIR"
rm -rf .gradle build app/build app/.cxx
log_info "Build artifacts cleaned"

# 9. Flutter clean (if Flutter is available)
if [ -n "$FLUTTER_SDK" ] && [ -d "$FLUTTER_SDK" ]; then
    log_info "Running Flutter clean..."
    cd "$PROJECT_ROOT"
    if command -v flutter &> /dev/null; then
        flutter clean
        flutter pub get
        log_info "Flutter dependencies refreshed"
    else
        log_warn "Flutter command not in PATH, skipping Flutter clean"
    fi
fi

# 10. Validate setup
log_info "Validating setup..."
VALIDATION_PASSED=true

if [ ! -f "$LOCAL_PROPS" ]; then
    log_error "local.properties not created"
    VALIDATION_PASSED=false
fi

if [ ! -d "$JNILIBS_DIR/arm64-v8a" ]; then
    log_error "jniLibs directory structure not created properly"
    VALIDATION_PASSED=false
fi

if [ ! -f "$ANDROID_DIR/app/build.gradle.kts" ]; then
    log_error "build.gradle.kts not found"
    VALIDATION_PASSED=false
fi

if [ "$VALIDATION_PASSED" = true ]; then
    echo ""
    echo "======================================"
    log_info "Setup completed successfully! ✓"
    echo "======================================"
    echo ""
    echo "Summary:"
    echo "  - Flutter SDK: ${FLUTTER_SDK:-Not found}"
    echo "  - Android SDK: $ANDROID_SDK"
    echo "  - NDK: ${NDK_VERSION:-Default from Flutter}"
    echo "  - jniLibs: Created with placeholders"
    echo ""
    echo "Next steps:"
    echo "  1. Build the debug APK:"
    echo "     cd $PROJECT_ROOT"
    echo "     flutter build apk --debug"
    echo ""
    echo "  2. Or build release APK:"
    echo "     flutter build apk --release"
    echo ""
    echo "Note: The first build may take longer as Gradle downloads dependencies."
    echo ""
else
    echo ""
    echo "======================================"
    log_error "Setup completed with errors"
    echo "======================================"
    echo ""
    echo "Please review the errors above and fix them manually."
    exit 1
fi
